CREATE TABLE workouts(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    bodypart TEXT NOT NULL,
    workout_name TEXT NOT NULL,
    workout_video TEXT NOT NULL,
    workout_desc TEXT NOT NULL
);